# netlify.toml (en la raíz del proyecto)

[build]
functions = "netlify/functions"

# Configuración de funciones
[functions]
external_node_modules = ["pg"]
node_bundler = "esbuild"
included_files = ["node_modules/pg/**/*"]

# Configuración de Node.js
[functions.environment]
NODE_OPTIONS = "--max-old-space-size=1024"

# Redirects para tu API
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/index/:splat"
status = 200
